#!/usr/bin/env bash
set -euo pipefail

staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

uv run ruff check . --fix
uv run ruff format

(cd prawobiorca-frontend && pnpm check)

if echo "$staged_files" | grep -q '^core-service/src/'; then
  uv run poe api_types
  git add core-service/openapi.json prawobiorca-frontend/src/api/generated
fi

if [ -n "$staged_files" ]; then
  echo "$staged_files" | xargs git add --
fi
