[project]
name = "prawobiorca"
version = "0.1.0"
description = "Law acts search engine with AI features."
license = "MIT"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "ruff==0.16.*",
    "mkdocstrings[python]==1.0.*",
    "zensical==0.0.67",
    "google-auth[requests]==2.59.*",
]

[tool.ruff]
extend = "ruff.toml"
