name: Setup backend
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v10.2.0
    - run: uv sync --locked
      shell: bash
    - run: cp core-service/.env.example core-service/.env
      shell: bash
